{{- if .Values.cert.createForWebApi }}
{{- if or (and (not .Release.IsInstall) (not .Release.IsUpgrade)) (and .Values.cert.webKey .Values.cert.webCrt) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "web-cert-name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
type: kubernetes.io/tls
data:
  tls.key: {{ .Values.cert.webKey }}
  tls.crt: {{ .Values.cert.webCrt }}
  jwt-rsa.key: {{ .Values.cert.jwtRsaKey }}
  jwt-rsa.pub: {{ .Values.cert.jwtRsaPub }}
{{- end }}
{{- end }}