apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stackgres-argo-helm
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sqlAgent/stackgres.git
    targetRevision: "1.3.1" 
    chart: stackgres-operator
  destination: 
    server: https://kubernetes.default.svc
    namespace: stackgres

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
