{{- if and .Values.deploy.restapi .Values.authentication (not .Values.authentication.secretRef.name) (eq .Values.authentication.type "jwt") }}
{{- $password := "" }}
{{- $clearPassword := "" }}
{{- if .Values.authentication.password }}
  {{- $password = (printf "%s%s" .Values.authentication.user .Values.authentication.password) | sha256sum }}
{{- else }}
  {{-  $secret := lookup "v1" "Secret" .Release.Namespace .Values.restapi.name }}
  {{- if $secret }}
    {{- if $secret.data }}
      {{- if $secret.data.password }}
        {{- $password = $secret.data.password | b64dec }}
      {{- end }}
      {{- if $secret.data.clearPassword }}
        {{- $clearPassword = $secret.data.clearPassword | b64dec }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- if or (and (not $clearPassword) (not $password)) .Values.authentication.resetPassword }}
    {{- $clearPassword = randAlphaNum 40 }}
    {{- $password = (printf "%s%s" .Values.authentication.user $clearPassword) | sha256sum }}
  {{- else }}
    {{- if not $password }}
      {{- $password = (printf "%s%s" .Values.authentication.user $clearPassword) | sha256sum }}
    {{- end }}
  {{- end }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.restapi.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
    api.stackgres.io/auth: user
type: Opaque
data:
  k8sUsername: {{ .Values.authentication.user | b64enc | quote }}
  password: {{ $password | b64enc | quote }}
  {{- if $clearPassword }}
  clearPassword: {{ $clearPassword | b64enc | quote }}
  {{- end }}
{{- end }}
